name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache CocoaPods
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
      working-directory: EssentialNews

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_14.2.app # Adjust Xcode version if necessary

    - name: Build and test
      run: xcodebuild clean build test -workspace EssentialApp.xcworkspace -scheme EssentialNews -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -testPlan EssentialNewsTests.xctestplan
      env:
        API_KEY: ${{ secrets.API_KEY }}
      working-directory: EssentialNews
